### ISSUE TITLE
libmemcached 1.0.17 won't compile on RHEL 6.4

### ISSUE THREAD

**Issue by m6w6** [awesomized/libmemcached#23]
* *Reported as:* [lp:1218521](https://bugs.launchpad.net/bugs/1218521)
 * *Reported by:* [lp:~bharper](https://launchpad.net/~bharper)
 * *Reported at:* 2013-08-29T17:23:45Z

Imported from Launchpad using lp2gh.

------------------------------------

Hello,

Unfortunately, I am unable to get libmemcached 1.0.17 to compile on RHEL 6.4.  The required version of bison went from 2.4 to 2.5 between the 1.0.16 and 1.0.17 releases.  RHEL 6.4 comes with bison 2.4.1.  If I just patch the parser.yy file to require version 2.4, I get the following error:

  CXX      libtest/libtest_libtest_la-runner.lo
  CXX      libtest/libtest_libtest_la-server.lo
  CXX      libtest/libtest_libtest_la-server_container.lo
  CXX      libtest/libtest_libtest_la-signal.lo
libtest/server_container.cc: In member function 'libtest::Server* libtest::server_startup_st::create(const std::string&, in_port_t, bool
)':
libtest/server_container.cc:241: error: 'HAVE_MEMCACHED_BINARY' was not declared in this scope
make[1]: *** [libtest/libtest_libtest_la-server_container.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_construct.h: In destructor 'libtest::Server::~Server()':
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_construct.h:99: warning: assuming that the loop counter do
es not overflow
make[1]: Leaving directory `/builddir/build/BUILD/libmemcached-1.0.17'
make: *** [all] Error 2

I get the same error on RHEL 5.9 without the patch.   With the patch I get:

+ make -j4
  GEN      libmemcached/csl/scanner.cc
"libmemcached/csl/scanner.l", line 38: unrecognized '%' directive
"libmemcached/csl/scanner.l", line 40: bad character: #
"libmemcached/csl/scanner.l", line 40: unknown error processing section 1
"libmemcached/csl/scanner.l", line 40: bad character: <
"libmemcached/csl/scanner.l", line 40: bad character: /
"libmemcached/csl/scanner.l", line 40: bad character: /
"libmemcached/csl/scanner.l", line 40: bad character: .
"libmemcached/csl/scanner.l", line 40: bad character: >
"libmemcached/csl/scanner.l", line 41: bad character: #
...

Please note the RHEL 5.9 comes with bison 2.3. I was able to build libmemcached 1.0.16 on RHEL 5.9 without any issues.  

Thanks,

Ben

**Comment by m6w6** [comment]
Lifted to 2.3 in db9fb0f9de0412cc5b757705fa19c9fa4dda8400
